version: '3'

services:
  order-service-app:
    container_name: order-service-app
    ports:
      - "8082:8082"
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true
