version: '3.9'

services:
  nginx:
    extends:
      file: ./spring/nginx/docker-compose.yml
      service: nginx
  
  authentication-service:
    extends:
      file: ./spring/authentication-service/docker-compose.yml

  product-service:
    extends:
      file: ./spring/product-service/docker-compose.yml

