version: '3.9'

services:
  master_db:
    image: mysql:8.0
    container_name: master_db
    restart: always
    volumes:
      - ./spring/master-db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./spring/master-db/scripts/init.sh:/docker-entrypoint-initdb.d/10-init.sh
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890@123
      MYSQL_DATABASE: kltech
    networks:
      - kltech-network
    entrypoint:
      - /bin/bash
      - -c
      - |
        docker-entrypoint.sh mysqld & sleep 10;
        mysql -uroot -p1234567890@123 <<EOSQL
        CREATE USER 'replica'@'%' IDENTIFIED WITH mysql_native_password BY '1234567890@123';
        GRANT REPLICATION SLAVE ON *.* TO 'replica'@'%' WITH GRANT OPTION;
        GRANT REPLICATION SLAVE ON *.* TO 'replica'@'authentication-service-db' WITH GRANT OPTION;
        GRANT REPLICATION SLAVE ON *.* TO 'replica'@'product-service-db' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOSQL
        wait




  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234567890@123
    networks:
      - kltech-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./spring/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true

