version: '3.9'

services:
  master_db:
    image: mysql:8.0
    container_name: master_db
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kltech 
      MYSQL_USER: replica
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  slave_db:
    image: mysql:8.0
    container_name: slave_db
    depends_on:
      - master_db
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kltech
      MYSQL_USER: replica
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    networks:
      - kltech-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./spring/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true

