version: '3.9'

services:
  authentication-service-db:
    image: mysql:latest
    container_name: authentication-service-db
    restart: always
    volumes:
      - ./docker/db/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/scripts/init.sh:/docker-entrypoint-initdb.d/10-init.sh
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890@123
      MYSQL_DATABASE: kltech
    networks:
      - kltech-network

  authentication-service-app:
    container_name: authentication-service-app
    ports:
      - 8082:8080
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://authentication-service-db:3306/kltech?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890@123
    depends_on:
      - authentication-service-db
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true

