version: '3.9'

services:
  authentication-service-app:
    container_name: authentication-service-app
    ports:
      - 8080:8080
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true
    