version: '3'

services:
  product-service-db:
    image: mysql
    container_name: product-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890@123
      MYSQL_DATABASE: kltech
    networks:
      - kltech-network

  product-service-app:
    container_name: product-service-app
    ports:
      - 8081:8080
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-service-db:3306/kltech?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890@123
    depends_on:
      - product-service-db
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true

