version: '3'

services:
  product-service-app:
    container_name: product-service-app
    ports:
      - "8081:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - kltech-network

networks:
  kltech-network:
    external: true

